database:
  uri: "mongodb+srv://jw:KvCA2WVHj9X8jYvM@mongodb-cluster.lfwlevw.mongodb.net/?retryWrites=true&w=majority"
  name: "brain-module"
  collection_metadata: "metadata"
  collection_modeldata: "modeladata"

paths:
  base_models_dir: "C:/Users/whsrj/bentoml/models"
  base_files_dir: "models"
  metadata_file: "metadata.json"
