database:
  uri: "mongodb+srv://jw:6Yh0dEoFllq0aL5g@mongodb-cluster.lfwlevw.mongodb.net/?retryWrites=true&w=majority"
  name: "brain-module"
  collection: "ml-metadata"

paths:
  base_models_dir: "C:/Users/whsrj/bentoml/models"
  base_files_dir: "models"
  metadata_file: "metadata.json"
