database:
  uri: "mongodb://localhost:27017/"
  name: "modelDB"
  collection: "metadata"

paths:
  base_models_dir: "C:/Users/whsrj/bentoml/models"
  base_files_dir: "models"
  metadata_file: metadata.json
